baseURL = 'http://localhost:1313/'
languageCode = 'zh-TW'
title = 'JConte'
theme = 'custom-theme'


[[menus.main]]
	name   = '首頁'
	url    = '/'
	weight = 1

[[menus.main]]
	name   = '標籤'
	url    = '/tags/'
	weight = 2

[[menus.main]]
	name   = '關於'
	url    = '/about/'
	weight     = 3


[[menus.main]]
	identifier = 'more'
	name       = '其他'
	url        = '#'
	weight     = 4


[[menus.main]]
	name   = '圖片檔'
	url    = '/gallery/'
	parent = 'more'
	weight = 3

[params.article]
	showToc = true
	tocTitle = '文章目錄'
	tocSticky = true
